//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSapunov
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreView
    {
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public int CountInStore { get; set; }
        public string NameManufacturer { get; set; }
    }
}
